package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class JuegoController {
	@FXML
	private Button TBadivinar;
	@FXML
	private Button BTsalir;
	@FXML
	private ImageView IdFigura;
	@FXML
	private Label PalabraOculta;
	
	@FXML
	private Label idtextorelleno;
	@FXML
	private TextField IdTexto;
	@FXML
	private Label IdVida;

	// Event Listener on Button[#TBadivinar].onMouseClicked
	@FXML
	public void ClickAdivinar(MouseEvent event) {
		// TODO Autogenerated
		
		if(this.IdTexto.getText().equals("r")) {
			PalabraOculta.setText("Pr _g_a_ _ _ _ _n");
		}else {
			IdVida.setText("4");
		}
	}
	// Event Listener on Button[#BTsalir].onMouseClicked
	@FXML
	public void ClickSalir(MouseEvent event) {
		// TODO Autogenerated
	}
}
